env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .jsx
        - .js
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  import/extensions: 0
  react/jsx-props-no-spreading: off
  no-console: off