env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  prettier/prettier: 
    - error
    - singleQuote: true
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .jsx
        - .js
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  import/extensions: 0
  react/jsx-props-no-spreading: off
  no-console: off
  object-curly-newline: 0
  comma-dangle: 0
  no-param-reassign:
    - error
    - props: false